### ISSUE TITLE
[error] terasort on spark rdma 

### ISSUE THREAD

**Issue by li7hui** [Mellanox/SparkRDMA#10]
Hi,
I was trying to run the terasort app on spark rdma. The terasort code is forked from https://github.com/ehiggs/spark-terasort

I can run the terasort datagen code successfully. However, the program fails when it uses the RDMA utilities.
![rdmaerror](https://user-images.githubusercontent.com/1718938/45195183-e9cfd700-b245-11e8-87cf-355bcde7e16f.png)

I checked the spark rdma install guide, but find no clue.

**Comment by petro-rudenko** [comment]
Hi, seems that you are running SparkRdma in a local mode (that's basically running executor in a separate thread and no network shuffle involved). Can you please provide command that you use to submit spark job. Basically you need to have:

1. RDMA capable network adapter.
2. Run in [spark standalone](http://spark.apache.org/docs/latest/spark-standalone.html) or in [spark yarn](http://spark.apache.org/docs/latest/running-on-yarn.html) modes with several executors on different physical machines.

Let me know if you'll have questions.

**Comment by li7hui** [comment]
Hi,
Thanks for quick response. The command I used to submit job is: 

./bin/spark-submit --class com.github.ehiggs.spark.terasort.TeraSort
/root/spark-terasort-1.0-SNAPSHOT-jar-with-dependencies.jar 
hdfs:///input hdfs:///output

**Comment by tobegit3hub** [comment]
Hi @li7hui ,

Have you run SparkRDMA in yarn-cluster mode? We have some problems when running the jobs in SparkRDMA because of it always use the wrong IP in another NIC. Do you have multiple network interface cards in the server? Or have you set the `LOCAL_SPARK_IP` in spark-env.sh?
