### ISSUE TITLE
TeraSort performance chart for README

### ISSUE THREAD

**Issue by yuvaldeg** [Mellanox/SparkRDMA#2]
![terasort_chart](https://user-images.githubusercontent.com/20062725/28947340-30d45c6a-7864-11e7-96ea-ca3cf505ce7a.png)

**Comment by petro-rudenko** [comment]
![image](https://user-images.githubusercontent.com/1121987/37929396-8d972354-3148-11e8-9e39-3bb903f1a71c.png)

**Comment by petro-rudenko** [comment]
@yuvaldeg is it ok?

**Comment by petro-rudenko** [comment]
![image](https://user-images.githubusercontent.com/1121987/37930562-cdc534f4-314b-11e8-927a-8454426c5d67.png)

**Comment by petro-rudenko** [comment]
![image](https://user-images.githubusercontent.com/1121987/37930913-cdc3591c-314c-11e8-9794-d30db5900751.png)

**Comment by petro-rudenko** [comment]
![image](https://user-images.githubusercontent.com/1121987/38248890-83097350-3752-11e8-8aba-5cc8ed89a9b2.png)

**Comment by petro-rudenko** [comment]
![image](https://user-images.githubusercontent.com/1121987/38266576-b752da0a-3781-11e8-8f60-65542db74312.png)

**Comment by petro-rudenko** [comment]
![image](https://user-images.githubusercontent.com/1121987/38267993-ac3089d4-3785-11e8-91f9-016d363a8fb1.png)

**Comment by petro-rudenko** [comment]
![image](https://user-images.githubusercontent.com/1121987/44669579-ec058a80-aa28-11e8-8ecf-4a66134021e6.png)

**Comment by petro-rudenko** [comment]
![image](https://user-images.githubusercontent.com/1121987/44670087-6c78bb00-aa2a-11e8-834c-71bc177abd87.png)

**Comment by petro-rudenko** [comment]
![qos](https://user-images.githubusercontent.com/1121987/46471155-bef38700-c7e1-11e8-9416-f2f0beef233c.png)
